--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/marcorgz1/Pictures/wallpapers/Arcade_decay_red.png"

-- Special
background="#0a0c0f"
foreground="#b3dcca"
cursor="#b3dcca"

-- Colors
color0="#0a0c0f"
color1="#545861"
color2="#843E45"
color3="#9E555B"
color4="#DB5F65"
color5="#838A7A"
color6="#709E8E"
color7="#b3dcca"
color8="#7d9a8d"
color9="#545861"
color10="#843E45"
color11="#9E555B"
color12="#DB5F65"
color13="#838A7A"
color14="#709E8E"
color15="#b3dcca"
