# Shell variables
# Generated by 'wal'
wallpaper='/home/marcorgz1/Pictures/wallpapers/Arcade_decay_red.png'

# Special
background='#0a0c0f'
foreground='#b3dcca'
cursor='#b3dcca'

# Colors
color0='#0a0c0f'
color1='#545861'
color2='#843E45'
color3='#9E555B'
color4='#DB5F65'
color5='#838A7A'
color6='#709E8E'
color7='#b3dcca'
color8='#7d9a8d'
color9='#545861'
color10='#843E45'
color11='#9E555B'
color12='#DB5F65'
color13='#838A7A'
color14='#709E8E'
color15='#b3dcca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
